### ISSUE TITLE
Blazor App has exception due to recent RetrievalMode change

### ISSUE THREAD

**Issue by Eilon** [Azure-Samples/azure-search-openai-demo-csharp#275]
If you run the Blazor Client App it gets a yellow Blazor error bar and this exception:

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/202643/2af2cdf2-76c9-4a4f-9c33-b54569e01e30)

```
blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'IMudRadioGroup' on object of type 'MudBlazor.MudRadio`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. The error was: MudRadioGroup<RetrievalMode> has a child MudRadio<System.String> with mismatching generic type.
System.InvalidOperationException: Unable to set property 'IMudRadioGroup' on object of type 'MudBlazor.MudRadio`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. The error was: MudRadioGroup<RetrievalMode> has a child MudRadio<System.String> with mismatching generic type.
 ---> MudBlazor.Utilities.Exceptions.GenericTypeMismatchException: MudRadioGroup<RetrievalMode> has a child MudRadio<System.String> with mismatching generic type.
   at MudBlazor.MudRadioGroup`1[[Shared.Models.RetrievalMode, Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CheckGenericTypeMatch(Object selectItem)
   at MudBlazor.MudRadio`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_IMudRadioGroup(IMudRadioGroup value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[MudRadio`1,IMudRadioGroup](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

The issue appears to have been introduced in this PR where the RetrievalMode was changed from a string to an enum: https://github.com/Azure-Samples/azure-search-openai-demo-csharp/pull/270

**Comment by Eilon** [comment]
PR to fix it is here: #276
